config/routes.rb
Rails.application.routes.draw do
  
  root to: 'posts#index'

  resources :posts do
    post 'save/:id', to: 'comments#save', as: 'save'
    collection do
      get :favorite
    end

    member do
      get :commentator
    end

    post 'comments/save'
    
    resources :comments, only: [:index, :new, :create]
  end

  get 'articles', to: 'posts#display_articles'
  resources :comments, only: [:destroy, :show, :edit, :update]

  delete 'erase/:id', to: "comments#erase", as: 'erase'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments #, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  

  # before nest: GET /comments
  # after nest: GET post/:post_id/comments
  def index
    # @comments = Comment.all
    @post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comments = @post.comments
  end

  # GET posts/:post_id/comments/:id
  def show
    @post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = Comment.find(params[:id])
  end

  # before nest: GET /comments/new
  # after nest: GET post/:post_id/comments/new
  def new
    @post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = @post.comments.build
  end

  # not nested
  def edit
    @comment = Comment.find(params[:id])

  end

  # POST posts/:post_id/comments
  def create
    @post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = @post.comments.build(comment_params)

    # alternative:
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    ##

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to post_comments_path(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # custom route namespaced by posts to 'comments#save'
  def save
    @post = Post.find(params[:post_id])
    #byebug
    respond_to do |format|
      @comment = @post.comments.create(comment_params)
      format.html { redirect_to post_comments_path(@comment.post), notice: 'Comment was successfully created' }
    end
  end

  # PATCH/PUT /comments/1
  def update
    #@post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        # @comments => post_comments_path(@post)
        format.html { redirect_to post_comments_path(@comment.post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 # modify path
  def destroy
    #@post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def erase
    #@post = Post.find(params[:post_id]) # <=> before_action :set_post
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # def set_post
    #   @post = Post.find(params[:post_id])
    # end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts/favorite
  def favorite
    @posts = Post.where(liked: true)
  end

  # GET /posts/:post_id/commentator
  def commentator
    @post = Post.find(params[:id])
    @commentator_name = @post.commentator_name
  end

  # GET /posts
  def index
    # the Javascript fetch() points to '/posts?f=""', with params[:f]="" not nil,
    # and is served by "posts#index":
    if params[:f].present?
      #puts params[:f].present? #=> in the logs 
    # after clic, render this as text since fetch() receives .txt
      @posts = Post.all
      render partial: 'posts/posts', locals: {posts: @posts}, layout: false
    else
    #   # on page load, show nothing
      @posts = []
    end
  end

  def display_articles
      @posts = Post.all 
      respond_to :js
  end

  # GET /posts/:id
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(post: @post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/:id/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/:id
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/:id
  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all #<=> dependent: :destroy in the model
    @post.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="row" data-id=<%= comment.id %>>
    <article >
        <h6 >Body: <%= comment.body %></h6>
        <%#= link_to 'Show Comments', post_comments_path(post) %>
        <%#= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy',comment_path(comment) , method: :delete, remote: true, data: { confirm: 'Are you sure to Destroy?' } %>
        <hr>
    </article>
</div>
<%#  %>
<%#  %>

app/views/comments/_form.html.erb
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

app/views/comments/_forms.html.erb
<div >
  <%= simple_form_for [@post, @comment], remote: true do |form| %>
    <%= form.input :body %>
    <%= form.button :submit, class:'btn btn-primary' %>
  <% end %>
</div>

app/views/comments/create.js.erb
document.querySelector('#article').insertAdjacentHTML('afterbegin',
    `<%= j render 'comments/comment', comment: @comment %>`)

app/views/comments/destroy.js.erb
document.querySelector('[data-id="<%= @comment.id %>"]').remove()

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%#= form_with(model: [@post, @comment], local: true) do |form| %>
<%= simple_form_for @comment do |form| %>
    <%= form.input :body %>
    <%= form.button :submit %>
<% end %>

    <%#= render 'form', form: form %>
  
<%# end %>
<%#= render 'form', comment: @comment %>

<%# link_to 'Show', @comment %> 
<%= link_to 'Back to list of comments of the post', post_comments_path(@comment.post) %>

app/views/comments/erase.js.erb
document.querySelector('[data-comment-id="<%=@comment.id %>"]').remove()

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<p>#views/comments/index.html.erb</p>
<h1>Comments for Post # <%= @post.id %></h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Body</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr data-comment-id="<%= comment.id %>">
        <td scope="row"><%= comment.body %></td>
        <td><%= link_to 'Show Post', @post %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Erase', erase_path(comment), method: :delete, remote: true, data: { confirm: 'Are you sure to Erase?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to all Posts', posts_path, class:"badge badge-info", style:"color:white;font-size:16px;" %> |

<%= link_to 'New Comment (with custom"save")', new_post_comment_path, class:"badge badge-info", style:"color:white;font-size:16px;" %> 

app/views/comments/new.html.erb
<h1>New Comment for Post # <%= @post.id %> (with custom "save")</h1>


<%= simple_form_for([@post,@comment], url: post_comments_save_path(@post)) do |f| %>
<%#= simple_form_for [@post,@comment], url: {controller: 'comments', action: "save"} do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>
    
<pre>
# comments#new
def new
  @post = Post.find(params[:post_id]) # <=> before_action :set_post
  @comment = @post.comments.build
end
</pre>
<pre>
#views/comments/new.html.erb
&lt%= form_with(model: [@post, @comment], local: true) do |form| %>

    &lt%= render 'comments/form', form: form %>
  
&lt% end %>
</pre>
<%= link_to 'Back to Comments of the post', post_comments_path, class:"badge badge-info", style:"color:white;font-size:14px;" %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post,@comment) %> |
<%= link_to 'Back', post_comments_path(@post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleNestForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
   </div>

    <% if Rails.env.development? %>
      <div class="container">
      <hr><hr>
          <div class="card">
              <div class="card-header">
                  Params
              </div>
              <div class="card-body">
                      <code>
                          <%= debug(params) %>
                      </code>
              </div>
          </div>
        </div>
      <% end %>
      
    

    

  </body>
</html>

app/views/posts/_form.html.erb
 <%= simple_form_for post do |form| %> 
  <%= form.error_notification %>
  <%= form.input :title %>
  <%= form.input :body %>
  <%= form.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<article style='display:inline-block; width: 340px;'>
    <div class="card">
        <div class="card-header">
            Title: <%= post.title %>
        </div>
        <div class="card-body">
            Body: <%= post.body %>
         </div>
        <div class="card-body">
            <%= link_to 'Show Comments', post_comments_path(post), class:"badge badge-info mybadge"%>
            <%= link_to 'Edit', edit_post_path(post), class:"badge badge-info mybadge" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Do you want to Destroy?' }, class:"badge badge-info mybadge" %>
       </div>
    </div>
</article>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <tr data-post-id="<%= post.id %>">
    <td scope="row"><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show & add comment', post_path(post) %></td>
    <td><%= link_to 'Show List of Comments', post_comments_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/posts/destroy.js.erb
document.querySelector('[data-post-id="<%= @post.id %>"]').remove()

app/views/posts/display_articles.js.erb
document.querySelector("#articles_list").innerHTML = ""
document.querySelector("#articles_list").insertAdjacentHTML('afterbegin',
`<%= j render @posts %>`)

app/views/posts/edit.html.erb
<h1>Editing Post #<%= @post.id %></h1>

<%= render 'posts/form', post: @post %>

<%= link_to 'Back', posts_path, class:"badge badge-info mybadge" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <h1>Index of Posts</h1>
</div>



<div class="row"> 
  <h5>1) Rendering with a table and iteration with <code>&lt% @posts.each do |post| %></code></h5>
  <br>

<button class="badge badge-info mybadge", id="index_posts">Show Post all</button>

  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Body</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody id='posts_list'>
     <%= render 'posts/posts', posts: @posts %>
    </tbody>
  </table>
</div>
<div class="row">
   <%= link_to 'New Post', new_post_path, class:"badge badge-info mybadge" %>
</div>
<div class="row">
 <p>We defined a button to display all the posts. On page load, the list is empty
We defined a JS <code>fetch() GET</code> function that triggers on this button click, 
which sends a dummy query string that points to the URL  `/posts`, sending `?f=""`.
This URL is served by the method 'posts#index'.
We put a dummy query string `f=""` such that we can differenciate the presence of params so
that the method `index` can react differently: an empty array `[]` on page load, and
`Post.all` when 'index' sees some params. Then we render a partial. Note that it is
important to use `locals: {posts: @posts}` for this to work (usually we don't need `locals`).
The JS `fetch()` asks for 'text/html' and parses the response from 'index' into 'text' with <code>response.text()</code>.
Then we just pass this content in the (unsual) form 'text/html' (parsed by Ruby, see in the console/network call) to render in
the view. Note: we need Turbolinks to be loaded to use the JS methods (see 'application.js')</p>

  <div class="col-md-6">
  <pre>
# post_controller.rb
def index
  if params[:f].present?
    @posts = Post.all
    render partial: 'posts/posts', locals: {posts: @posts}, layout: false
  else
  #   # on page load, show nothing
    @posts = []
  end
end
  </pre>
  
  </div>
  <div class="col-md-6">
 

  <pre>
#/packs/components/fetchPosts.js
const fetchPosts = (tag) => {
  document.querySelector(tag).addEventListener("click", (e) => {
    e.preventDefault();
    try {
      const query = await fetch('/posts?f=""', {
        method: "GET",
        headers: {
          "Content-Type": "text/html",
          Accept: "text/html",
        },
        credentials: "same-origin", // default value
      });
      if (query.ok) {
        const content = await query.text();
        return (document.querySelector("#posts_list").innerHTML = content);
      }
    } catch (error) {
      throw error;
    }
  });
};

export { fetchPosts };


  </pre>
  </div>
</div>



<br>


<div class="row">
  <h5>2) Other possibility: rendering with <code>&lt%= render @posts %></code> 
  with the partial <em>#views/posts/_post.html.erb</em>. We used <code>style='display:inline-block'</code> 
  to have a flex-like display.</h5>

</div>
<%= link_to 'Show All Articles', articles_path, remote: true, id:"article_btn", class:"badge badge-info mybadge" %>
<p>We have another Ajax method to render. The link <code>remote: true</code> above points to the `posts#display_articles` method where
we just defined the <code>respond_to</code> to <em>format.js</em>,  which renders the view '/posts/display_articles.js.erb'.
Note: we need <code>insertAdjacentHTML</code> and not just <em>innerHTML</em> for this to work.</p>
<pre>
document.querySelector("#articles_list").innerHTML = ""
document.querySelector("#articles_list").insertAdjacentHTML('afterbegin',
`<%= j render @posts %>`)
</pre>
<div id="articles_list">
<!-- RENDERING A COLLECTION -->
  <%= render @posts %>
  <!--  above is shorthand for %= render partial: 'posts/post', collection: @posts %-->
</div>
<div class="row">
<h5>3) Importing <em>.js</em> libraries into <em>.js.erb</em> files</h5>
<p>To add Erb support in your JS templates, run <code>bundle exec rails webpacker:install:erb</code> 
on a Rails app already setup with Webpacker. We then can create a <em>.js.erb</em> file in the
folder <em>/javascript/packs</em>. Then we can use <em>ERB</em> (Ruby parses it first) and
external libraries with <code>import { myFunction } from '../components/myJsFile.js</code>. 
</p>
<p> Note 1: A 'standard' view rendering file <em>.js.erb</em> located in the views does <strong>not</strong>
have access to <em>import</em>, only those located in the folder <em>/javascript/packs/</em> do
 (after running <em>webpacker:install:erb)</em></p>
<p>Note 2: To use a <em>JS</em> library inside a view <em>.html.erb</em>, we need to:</p>
<ul>
  <li>import the library in a <em>someFile.js.erb</em> file in <em>/javascript/packs</em></li>
  <li>import the <em>someFile.js.erb</em> file in the view with <code>&lt%= javascript_pack_tag 'someFile' %></code></li>
</ul>  

<p>Note 3: we need to have Turbolinks loaded to access to the DOM, so all the code in the 
<em>someFile.js.erb</em> file is a callback: <code>document.addEventListener("turbolinks:load", myFunction})</code> 
and declare <code>const myFunction = ()=> {[...]}</code> after.
</p>

<p>
Note 4: This can save on _data-attributes_ (the <code>`data-something="&lt%= Post.first.id%>"`</code> in the HTML file
 with it's searching <code>`document.querySelector('[data-something]')` </code>can be replaced simply by eg
  <code>`const id = &lt%= Post.first.id%> </code> in the _.js.erb_ file)
</p>
</div>
<div id="test" data-id="<%= Post.first.id %>">Appended by  <em>hello_erb.js.erb</em> using an external library:</div>
<%= javascript_pack_tag 'hello_erb' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"badge badge-info", style:"color:white;font-size:16px;" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>#views/posts/:post_id</p>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">Post # <%= @post.id %></div>
        <div class="card-body">
        <p><strong>Title:</strong> <%= @post.title %></p>
        <p><strong>Body:</strong> <%= @post.body %></p>
        <p><%= link_to 'Edit post', edit_post_path(@post), class:"badge badge-info mybadge" %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="card">
        <div class="card-header">Code for nested form: creation of a <em>comment</em> inside a <em>post</em></div>
        <div class="card-body">

        <pre>
#posts_controler.rb
def show
  @post = Post.find(params[:id])
  @comment = Comment.new(post: @post)
end

#views/posts/:post_id
&lt%= form_with(model: [@post, @comment],  url: {controller:"comments", action: "save"} local: true) do |form| %>
  &lt%= render 'comments/form', form: form %>
&lt% end %>
          </pre>
          
        </div>
      </div>
    </div>
  
    <div class="col-md-5">
      <div class="card">
        <div class="card-header">Create a new comment (Ajax - create)</div>
        <div class="card-body">       
            <%= render 'comments/forms' %>
        </div>

        <pre>
&ltform action="/posts/1/comments" accept-charset="UTF-8" data-remote="true" method="post">
&lttextarea name="comment[body]" id="comment_body">&lt/textarea>
&ltinput type="text" value="1" name="comment[post_id]"> 
&ltinput type="submit" name="commit" value="Create Comment" data-disable-with="Create Comment">
&lt/form>
        </pre>

      </div>
    </div>
  </div>


  <div class="row">
    <div class="col">
        <%= link_to 'Back to all Posts', posts_path, class:"badge badge-info", style:"color:white; font-size:14px;" %>
    </div>
  </div>
  <hr>
  <h4>Comments appear below with Ajax and can de delete by Ajax</h4>
  <hr>
  <div id="article">
    <%= render @post.comments %>
  </div>  
</div>

app/views/shared/_errors.html.erb
<% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>